### ISSUE TITLE
Error ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by presb** [Unrud/RadicaleInfCloud#4] opened 2017-08-18 13:02 UTC
Hello,
I have just installed Radicale on a Raspberry Pi. It works fine with Thunderbird client.
I try to add RadicaleInfCloud to access by Firefox. I can log in at http://192.168.xxx.xxx:5232 and there is a link InfCloud on the top. When I click I get an empty page, and firefox console shows many ERR_CONTENT_LENGTH_MISMATCH errors.
What's the matter ?
Many thanks for your good work !

**Comment by Unrud** [comment] 2017-08-18 16:52
Does Radicale log any error messages?
Otherwise, can you create a dump of the network traffic on the Raspberry Pi, while you are trying to open http://192.168.xxx.xxx:5232/.web/infcloud?

You can create a dump with something like:
```
sudo tcpdump -i any -s 0 -w output.dump tcp port 5232
```
The command writes all TCP packets with source or destination port 5232 to the file **output.dump**.
Keep in mind that the dump contains IP and MAC addresses, you can use [TraceWrangler](https://www.tracewrangler.com/) to anonymize them.

**Comment by presb** [comment] 2017-08-18 18:32
I don't find Radicale log in /var/log
Where are they?

Here is the dump:
[output.zip](https://github.com/Unrud/RadicaleInfCloud/files/1235302/output.zip)

Thanks for your help.

**Comment by Unrud** [comment] 2017-08-18 19:36
> Where are they?

This depends on your configuration, by default the log is written to ``stderr``.

**Comment by presb** [comment] 2017-08-18 20:34
stderr don't exist. I can't find log anywhere.
Maybe I must add a parameter to the /etc/radicale/config to have log ?

**Comment by Unrud** [comment] 2017-08-24 12:38
> stderr doesn't exist. I can't find log anywhere.
> Maybe I must add a parameter to /etc/radicale/config to have log ?

``stderr`` is one of the [standard streams](https://en.wikipedia.org/wiki/Standard_streams). The errors are printed in the terminal.

> After a good search, I successfully enabled log.

The log doesn't contain any errors, that's probably the reason why you didn't see anything on the terminal.

This is a duplicate of https://github.com/Kozea/Radicale/issues/687. Update to Python >= 3.5 or try the workaround in the issue.

**Closed by Unrud** 2017-08-24 12:38 UTC

**Comment by presb** [comment] 2017-08-24 13:16
Thank you very much.
The solution timeout = 0 works fine !
My version of python is 3.4
There isn't newer version in raspbian repository. I will expect easily because the problem is solved.
Many thanks !
